#!/bin/bash

set -o noglob
if test -z "$USER" ;then
  echo "USER not set" 1>&2
  exit 1
fi
usage="Usage: $0 username [-l] [ALL|NONE]|[+-]hostglobs..."
case "$1" in
   -*) echo "$usage"; exit 1;;
esac


username=$1;shift
if test -z "$1" ;then
   echo "$usage"
   exit 1
fi

host=ldap.gnmedia.net
baseuserdn="ou=People,dc=gnmedia,dc=net"
basegroupdn="ou=Groups,dc=gnmedia,dc=net"
binddn="uid=$USER,$baseuserdn"

echo -n "($binddn)'s LDAP password: "
stty -echo
read password
stty echo
echo

ldapargs="-D $binddn -h $host"
openldapargs="-w $password -x $ldapargs"

testlist=$(ldapsearch $openldapargs -LLL "(uid=$username)" host)
if [ $? != 0 ];then
   exit 1
fi
if [ $1 = "-l" ];then
   echo "$testlist"
   exit
fi
for host in "$@";do
   case $host in
       -*) # remove it
           host=${host/-/}
           ldapsearch $openldapargs -LLL -b uid=$username,$baseuserdn "(host=$host)" cn | grep -q ^cn && \
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\ndelete: host\nhost: $host" | ldapmodify $openldapargs
          ;;
       NONE) # remove all
           host=${host/-/}
           ldapsearch $openldapargs -LLL -b uid=$username,$baseuserdn "(host=*)" cn | grep -q ^cn && \
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\ndelete: host" | ldapmodify $openldapargs
          ;;
       "*"|ALL) # remove all, add *
           ldapsearch $openldapargs -LLL -b uid=$username,$baseuserdn "(host=*)" cn | grep -q ^cn && \
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\ndelete: host" | ldapmodify $openldapargs
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\nadd: host\nhost: *" | ldapmodify $openldapargs
           ;;
       *) # add it
           host=${host/+/}
           ldapsearch $openldapargs -LLL -b uid=$username,$baseuserdn "(host=\*)" cn | grep -q ^cn && \
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\ndelete: host\nhost: *" | ldapmodify $openldapargs 2>/dev/null
           ldapsearch $openldapargs -LLL -b uid=$username,$baseuserdn "(host=$host)" cn | grep -q ^cn || \
           echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\nadd: host\nhost: $host" | ldapmodify $openldapargs
          ;;
   esac
done 

echo "Generating new access.conf..."
ldapsearch $openldapargs -LLL "(uid=$username)" host
accessconfgen

