#!/bin/bash

set -o noglob
if test -z "$USER" ;then
  echo "USER not set" 1>&2
  exit 1
fi
usage="Usage: $0 username newpassword"
case "$1" in
  -*) echo "$usage"; exit 1;;
esac

username=$1;shift
newpassword=$1;shift
if test -z "$newpassword" ;then
   echo "$usage"
   exit 1
fi
if [ "$USER" = "$username" ];then
   echo "Refusing to reset your password. Silly monkey."
   exit 1
fi

host=ldap.gnmedia.net
baseuserdn="ou=People,dc=gnmedia,dc=net"
basegroupdn="ou=Groups,dc=gnmedia,dc=net"
binddn="uid=$USER,$baseuserdn"

echo -n "($binddn)'s LDAP password: "
stty -echo
read password
stty echo
echo

ldapargs="-D $binddn -h $host"
openldapargs="-w $password -x $ldapargs"

testlist=$(ldapsearch $openldapargs -LLL "(uid=$username)" uid)
if [ $? != 0 ];then
  exit 1
fi
if [ -z "$testlist" ];then
   echo "No such user"
   exit 1
fi

# Sssh, don't tell the cryptologist about this...
salt=\$1\$$(set -- $((echo $RANDOM $$ `date`; cat /etc/passwd) | md5sum); echo $1 | head -c 8)\$
newcrypt=$(echo "$newpassword" "$salt" | perl -e 'split(" ",<>);print(crypt($_[0],$_[1]));')

if [ -n "$testlist" ];then
   echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\ndelete: userPassword" | ldapmodify $openldapargs
fi
echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\nadd: objectClass\nobjectClass: shadowAccount" | ldapmodify $openldapargs 2>/dev/null
echo -e "dn: uid=$username,$baseuserdn\nchangetype: modify\nadd: userPassword\nuserPassword: {CRYPT}$newcrypt" | ldapmodify $openldapargs

echo "Password has been reset"
