#!/bin/bash

# gstaples @ Gorilla Nation

loc=lax

echo "Checking for VMs on offline hosts..."
for server in $(nodels vm@lax vm.host | awk '{print $2}');do
   if ! nodels $server groups | grep -q online;then
     echo "Vacating $server because it is not online"
     metalvacate $server
   fi
done
echo OK

echo "Checking for misbalance..."
nodels vm@$loc vm.host | sort -k 2 | uniq -c -f 1 | sort -rn | awk '{print $1" "$3}'

x=$(nodels vm@$loc vm.host | sort -k 2 | uniq -c -f 1 | sort -rn | awk '{print $1}' | sort -u | wc -l)
while [ $x -gt 2 ];do
   vm=$(nodels vm@$loc vm.host | sort -k 2 | uniq -c -f 1 | sort -rn | head -1 | awk '{print $2}' | sed 's/://')
   echo "Moving $vm"
   rmigrate $vm $(metalallocator1 $loc)
   nodels vm@$loc vm.host | sort -k 2 | uniq -c -f 1 | sort -rn | awk '{print $1" "$3}'
   x=$(nodels vm@$loc vm.host | sort -k 2 | uniq -c -f 1 | sort -rn | awk '{print $1}' | sort -u | wc -l)
done
echo Balanced
