#!/bin/bash

# gstaples @ Gorilla Nation

PATH=/opt/xcat/bin:/opt/xcat/sbin:$PATH

nodes=$(nodels $1)
shift
if [ -z "$nodes" ];then
   exit 1
fi
if [ $(echo "$nodes" | wc -w) -gt 1 ];then
   echo "only one node allowed" 1>&2
   exit 1
fi

exec ssh $nodes $@
