#!/bin/bash

# Restores lab to fully working webapp
# Complete with rip van winkle effect...

if [ $(id -u) != 0 ];then
    echo "Only as root" 1>&2
    exit 1
fi

/etc/init.d/httpd stop
killall httpd
/etc/init.d/mysqld stop
killall mysqld mysqld_safe

/bin/rm /var/run/httpd/.backups/*
umount /mnt/apache /mnt/docroots /var/run/httpd
sed -i /httpd/d /etc/fstab
#ssh nfs1.netapp3.gnmedia.net snap restore -f -t vol -s lab_clean_master nfs1_app1v_lab_tp_dev_lax_data
cd /mnt/mysql
rsync -av --delete --exclude=.snapshot .snapshot/lab_clean_master3/ .
mount -a

rm -rf /mnt/apache/* /mnt/docroots/*

cd /tmp || exit
rm -rf labscripts
svn export https://svn.gnmedia.net/sysadmins/trunk/labscripts || exit
cd labscripts/newroot || exit
svn up || exit
cp -rvfp * / || exit
touch -d yesterday /mnt/docroots/crucialmonthlyreport.gnmedia.net/old/monthly_earnings.php.bak
/sbin/service mysqld start
/sbin/service httpd start
/usr/sbin/puppetd -tv
/sbin/service puppet start
cd /
rm -rf /tmp/labscripts
