#!/bin/sh
#
# Compare configs in core2 ACE contexts to those in core1.
#
# Written by Dairenn Lombard & Hondo Cabral

# Only enable this for debugging
# set -x

core1="core1.gnmedia.net"
core2="core2.gnmedia.net"

confpath="/app/shared/var/rancid/configs"
diffpath="/app/shared/rancid/home"

echo; echo "Comparing ACE context configs in core2 to those in core1 and saving lines"
echo "unique to core2 to $diffpath.  Please wait."

echo -n "Processing: "
for file in `ls -1 $confpath/*.ace1.$core2`
do
	context=`echo "$file" | cut -d "/" -f 7`
	compfile=`echo $context | sed s/$core2/$core1/`
	grep -x --file=$confpath/$compfile -v $confpath/$context > $diffpath/$context.delta
	echo -n "."
done
echo ; echo "Done.  Files written:"
ls -1 $diffpath/*.delta
echo
