#!/bin/sh
#
# Product ACE context configs without entries unique to each core.
#
# Written by Dairenn Lombard & Hondo Cabral

# Only enable this for debugging
# set -x

core1="core1.gnmedia.net"
core2="core2.gnmedia.net"

confpath="/app/shared/var/rancid/configs"
diffpath="/app/shared/rancid/home"

echo; echo "Comparing ACE context configs in core2 to those in core1 and saving lines"
echo "that match both switches to $diffpath.  Please wait..."

echo -n "Processing: "
for file in `ls -1 $confpath/*.ace1.$core2`
do
	context=`echo "$file" | cut -d "/" -f 7`
	compfile=`echo $context | sed s/$core2/$core1/`
	# Print only the lines that match in the comparison config file
	grep -x --file=$confpath/$compfile $confpath/$context > $diffpath/$context.mirror
	echo -n "."
done
echo ; echo "Done.  Files written:"
ls -1 $diffpath/*.mirror
echo
