#!/bin/bash

if [ -z "$1" ];then
   echo "Usage: $0 URL"
   exit 1
fi

# This app is on one box, no vip, but has an fwsm entry. The hostname points to the external IP. 

curl -H "Host:utils.atomiconline.com" http://admin:kw7RAx4gw4B@vip-app-extutils.tp.prd.lax.gnmedia.net/utilities/akamai_content_refresh.cgi?url=$1
echo
