#!/usr/bin/perl

$sleep=10;
$vip="VIP-NGX-CI.CI.PRD.LAX";
$domain="test-ci.gnmedia.net";
$uri="/widgets/17";

open(LOG,">>/var/log/ciperfmon.log") or die;
select(LOG);

while(1) {
   #print scalar localtime, " Loading...\n"; 
   open(ACE,"aceman sfarm $vip | grep -A 1 rserver:|") or die;

   #rserver: NGX1V-CI.CI.PRD.LAX
       #10.11.34.105:0        8      OPERATIONAL  0          12789      159

   while ($_=<ACE>) {
      @_=split;
      if ($_=~/rserver/) {$rserver=$_[1]}
      else {
         $cons{$rserver}{new}=$_[4];
         $cons{$rserver}{time}=`/usr/bin/time  curl -H "host: $domain" http://$rserver/$uri 2>&1 >/dev/null  | awk '/elapsed/ {print \$3}' | sed s/elapsed//`;
         chomp($cons{$rserver}{time});
   
         if ($cons{$rserver}{old}) {
            printf "%s $rserver: %0.2f cons/sec %s\n",scalar localtime,($cons{$rserver}{new}-$cons{$rserver}{old})/$sleep,$cons{$rserver}{time};
         }
         $cons{$rserver}{old}=$cons{$rserver}{new};
              
      }
   }
   close(ACE);
   #$time=`/usr/bin/time  curl -H "host: widget.crowdignite.com" http://widget.crowdignite.com/$uri 2>&1 >/dev/null  | awk '/elapsed/ {print \$3}' | sed s/elapsed//`;
   $time=`/usr/bin/time  curl -H "host: $domain" http://test-ci.gnmedia.net/$uri 2>&1 >/dev/null  | awk '/elapsed/ {print \$3}' | sed s/elapsed//`;
   chomp($time);
   printf "%s test-ci.gnmedia.net: %s\n",scalar localtime,$time;
   $|=1; $|=0;
   sleep($sleep);
}
