#!/usr/bin/perl

@names=(<STDIN>);
chomp @names;
print join("\n", sort {
   $a =~ m/([^ ]+)/;
   $aname = $1;
   $b =~ m/([^ ]+)/;
   $bname = $1;
   @partsa=reverse split(/[-.]/,$aname);
   @partsb=reverse split(/[-.]/,$bname);
   foreach $i (0..$#partsa) {
      if ($partsa[$i] eq $partsb[$i]) {
         next;
      }
      return $partsa[$i] cmp $partsb[$i];
   }
} @names);
print "\n";
