#!/bin/bash

set -o noglob
if test -z "$USER" ;then
  echo "USER not set" 1>&2
  exit 1
fi
usage="Usage: $0 username"

case "$1" in
   -*) echo "$usage"; exit 1;;
esac


username=$1;shift
if test -z "$username" ;then
   echo "$usage"
   exit 1
fi

host=ldap.gnmedia.net
baseuserdn="ou=People,dc=gnmedia,dc=net"
basegroupdn="ou=Groups,dc=gnmedia,dc=net"
binddn="uid=$USER,$baseuserdn"

echo -n "($binddn)'s LDAP password: "
stty -echo
read password
stty echo
echo

ldapargs="-D $binddn -h $host"
openldapargs="-w $password -x $ldapargs"

testlist=$(ldapsearch $openldapargs -LLL -b $basegroupdn "(memberUid=$username)" cn)
if [ $? != 0 ];then
   exit 1
fi
if [ "$1" = "-l" ];then
   echo "$testlist"
   exit
fi

read -p "Are you sure? [y/N] " prompt
case $prompt in
  y) :;;
  *) echo "Cancelled."; exit;;
esac

for group in $(ldapsearch $openldapargs -LLL "(memberUid=$username)" cn | grep ^cn | awk '{print $2}');do
  echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: memberUid\nmemberUid: $username" | ldapmodify $openldapargs
done
for group in $(ldapsearch $openldapargs -LLL "(uniqueMember=uid=$username,$baseuserdn)" cn | grep ^cn | awk '{print $2}');do
  echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: uniqueMember\nuniqueMember: uid=$username,$baseuserdn" | ldapmodify $openldapargs
done

ldapdelete $openldapargs cn=$username,$basegroupdn
ldapdelete $openldapargs uid=$username,$baseuserdn
