#!/usr/bin/perl -w

use strict;
use DNS::ZoneParse;
use Data::Dumper;
use WebService::Amazon::Route53;
use File::Basename;
use Getopt::Std;

my $zone = $ARGV[0];
if (not defined $zone) {
  die "Usage:\n\t$0 <HOSTNAME>\n";
}
$zone =~ s{\.[^.]+$}{};
$zone = basename($zone);
$zone=$zone.".";

use constant AWS_ID => 'AKIAJKZPO45Y4YPYZPKQ';
use constant AWS_SECRET => '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';
# set ALERT_EMAIL to FALSE to disable email alerts.
use constant ALERT_EMAIL => 'q_la@evolvemediallc.com';
use constant INFO_EMAIL => 'q_cm@evolvemediallc.com';
use constant WIN_EMAIL => 'q_wachange@rt.gnmedia.net';


# lets check if the zone exists on r53.
my $myTime=time();
my $r53 = WebService::Amazon::Route53->new(id => AWS_ID, key => AWS_SECRET);
my $myzone = $r53->find_hosted_zone(name => $zone);
if ($myzone){
    print "$zone exists\n";
    exit;
} else {
    print "$zone does not exist\n";
    exit 1;
}
