#!/bin/bash

source=$1
dest=$2

md5=$(echo $source | md5sum | awk '{print $1}')

sfiler=${source%%:*}
spath=${source##*:}
svolume=$(echo $spath | sed -e 's/^\/vol\///' -e 's/\/.*//')
spath=$(echo $spath | sed -e "s/^\/vol\/$svolume//" -e 's/.*\//\//')
dfiler=${dest%%:*}
dpath=${dest##*:}
dvolume=$(echo $dpath | sed -e 's/^\/vol\///' -e 's/\/.*//')
dpath=$(echo $dpath | sed -e "s/^\/vol\/$dvolume//" -e 's/.*\//\//')

if [ -z "$sfiler" -o -z "$svolume" -o -z "$dfiler" -o -z "$dvolume" ];then
    echo "Usage: $0 <filer:/source> <filer:/destination>"
    exit 1
fi

echo -- "$sfiler" "$spath"   "$dfiler" "$dpath" 

if mount | grep -q /mnt/rsynccopy/$md5/source;then
    sudo umount /mnt/rsynccopy/$md5/source || exit 1
fi
if mount | grep -q /mnt/rsynccopy/$md5/destination;then
    sudo umount /mnt/rsynccopy/$md5/destination || exit 1
fi


rnetapp $sfiler snapshot delete $svolume rsynccopy >/dev/null
rnetapp $sfiler snapshot create $svolume rsynccopy
rnetapp $sfiler exports add /vol/$svolume $(hostname)
rnetapp $dfiler exports add /vol/$dvolume $(hostname)
sudo mkdir -p /mnt/rsynccopy/$md5/{source,destination}

sudo mount $sfiler:/vol/$svolume/.snapshot/rsynccopy/$spath /mnt/rsynccopy/$md5/source || exit 1
sudo mount $dfiler:/vol/$dvolume /mnt/rsynccopy/$md5/destination || exit 1
echo "Starting rsync"
sudo mkdir -p /mnt/rsynccopy/$md5/destination/$spath
sudo rsync -av /mnt/rsynccopy/$md5/source/ /mnt/rsynccopy/$md5/destination/$spath
sudo umount /mnt/rsynccopy/$md5/source
sudo umount /mnt/rsynccopy/$md5/destination

mount | grep -q /vol/$svolume || rnetapp $sfiler exports remove /vol/$svolume $(hostname)
mount | grep -q /vol/$dvolume || rnetapp $dfiler exports remove /vol/$dvolume $(hostname)

