#!/bin/bash

# gstaples @ Gorilla Nation

PATH=/opt/xcat/bin:/opt/xcat/sbin:$PATH

nodes=$(nodels $1)
shift
if [ -z "$@" ];then
   if [ $(echo "$nodes" | wc -w) -gt 1 ];then
      echo "only one node allowed in interactive mode"
      exit 1
   fi
   virsh -c qemu+ssh://root@$nodes/system
else

   for node in $nodes;do
      virsh -c qemu+ssh://root@$node/system "$@" 2>&1 | sed "s/^/$node: /"
   done
fi
