#!/bin/bash

ntests=10
tests="movieguide.comingsoon.net 10.2.50.133
movieguide.comingsoon.net 10.2.10.80"

echo "$tests" | while read hostname ip;do
   failed=0
   echo -n "Testing $hostname -> $ip"
   for a in $(seq 1 $ntests);do
      curl --max-time 2 -I -H "host: $hostname" $ip  >/dev/null 2>&1
      res=$?
      if test $res != 0;then echo -n "($res)"; failed=$((failed+1)); else echo -n "." ;fi
      echo -n .
   done
   echo " Failed: $failed/$ntests"
done
