#!/bin/bash

noder=$1
domain=$2
url=$3

if [ -z "$domain" ];then
   echo "Usage: $0 noderange domain [urlpath]"
   echo "Example: xhosthack app@jm@prd www.craveonline.com gaming/articles/182905-10-dream-games-we-want-to-see-happen"
   exit 1
fi

for node in $(nodels $noder);do
   curl --progress-bar -I -H "host: $domain" "http://$node/$url" 2>&1 </dev/null | sed 's/\(.*\)/'$node': \1/' &
done | sort
wait
