#!/bin/bash

#set -x

NOREV=0000000000000000000000000000000000000000

#look at user of commit and reject if it's not a valid ldap user 

while read oldrev newrev ref; do

    # ignore new branch creations
    if [[ $oldrev = $NOREV ]]; then
        exit 0
    else 

        # Check the list of incoming commits
        all_revs=`git rev-list $oldrev..$newrev`
        for rev in $all_revs; do
	    commit_name=$(git log -1 --pretty="%an" $rev)

                 if [[ $commit_name != $GL_USER ]]; then
                     echo
                     echo "COMMIT FAILED: Please configure your git name as $GL_USER." 
                     echo "Right now it is configured as $(git log -1 $rev |awk '{print $2,$3}'|sed -n '2p')!"
                     echo 'To change the author: git commit --amend --author="'$GL_USER'"'
                     echo 'To fix permanently going forward: git config user.name "'$GL_USER'"'
                     exit 1 
                 fi
         done
    fi
done
