#!/bin/bash


# require bind to get /usr/sbin/named-checkzone
set -e

DOMAIN_PATH=${1?"Usage: $0 ARGUMENT"}

if [ -r ${DOMAIN_PATH} ] ; then
    echo "Testing ${DOMAIN_PATH}"

    # FIXME: shouldn't assume .hosts extension
    ZONE=$(basename ${DOMAIN_PATH} .hosts)

    # checking the soa, assumed : first mention of 'serial' is for the serial of the zone ' ; serial'
    # FIXME: shouldn't assume serials are marked by the proper comment
    SERIAL=$(grep -i serial ${DOMAIN_PATH} | cut -d ';' -f 1 | head -n 1)
    SERIAL="${SERIAL//[[:space:]]}"

    # check serial is not in the future
    if (( "${SERIAL}" > "$(date +%Y%m%d99)" )); then
        echo "Serial ${SERIAL} is too high for ${ZONE}"
        exit 1
    fi

    # Check serial not in the past (or most likely not updated) 
    if (( "${SERIAL}" < "$(date +%Y%m%d00)" )); then
        echo -e "Serial ${SERIAL} should be starting with $(date +%Y%m%d) for ${ZONE} \n(considering ${ZONE} has been updated today)\n\nUse $ dnsupdateserial ZONE_FILE on deploy or xcat"
        exit 1
    fi


    # checking the zone itself
    /usr/sbin/named-checkzone ${ZONE} ${DOMAIN_PATH}
    
fi
