#!/bin/bash

cd $(dirname $0)
if [ ! -d app1v-dnsint ];then
   echo "Where is the app1v-dnsint directory?" 1>&2
   exit 1
fi

generatemaster() {
  area=$1
  master=$2
  for file in $(cd ../../zones/;echo *.rev *.hosts $area/*.rev $area/*.hosts);do
     if [ ! -f ../../zones/$file ];then # ignore a weird symlink, not that this has happened
         continue;
     fi

     case $file in
        *.hosts) zone=$(basename ${file%.hosts}).;;
        *.rev) zone=$(IFS=. ; set -- ${file#*/}; echo $3.$2.$1.in-addr.arpa);;
     esac


     cat <<-__EOF__
	zone "$zone" IN {
	    type master;
	    notify yes;
	    file "$file";
	    allow-transfer { $master };
	    allow-query { any; };
	};

	__EOF__
     done
}

set -x 
cd app1v-dnsext 
master="localhost; 10.64.81.86; 10.64.81.160; 10.64.81.189; 10.64.81.168; 10.64.81.126;"
generatemaster external "$master" > named-zones-generated.conf
cd ..

cd app1v-dnsint 
master="localhost; 10.64.81.86; 10.64.81.160; 10.64.81.189; 10.64.81.168; 10.64.81.126;"
generatemaster internal "$master" > named-zones-generated.conf
cd ..

set +x
