#!/bin/bash

cd $(dirname $0)
if [ ! -d app1v-dnsint ];then
   echo "Where is the app1v-dnsint directory?" 1>&2
   exit 1
fi

generatemaster() {
  area=$1
  master=$2
  for file in $(cd ../../zones/;echo *.rev *.hosts $area/*.rev $area/*.hosts);do
     if [ ! -f ../../zones/$file ];then # ignore a weird symlink, not that this has happened
         continue;
     fi

     case $file in
        *.hosts) zone=$(basename ${file%.hosts}).;;
        *.rev) zone=$(IFS=. ; set -- ${file#*/}; echo $3.$2.$1.in-addr.arpa);;
     esac


     cat <<-__EOF__
	zone "$zone" IN {
	    type master;
	    notify yes;
	    file "$file";
	    allow-transfer { $master };
	    allow-query { any; };
	};

	__EOF__
     done
}


cd app1v-dnsext || exit 1
master="localhost; 67.15.66.42; 67.15.66.43; 64.34.172.209; 72.51.41.238;"
generatemaster external "$master" > named-zones-generated.conf
cd ..

cd app1v-dnsint || exit 1
master="localhost; 10.11.20.68; 10.11.20.69; 10.11.20.53; 10.11.20.88; 10.11.220.46; 10.11.20.133; 10.100.10.21;"
generatemaster internal "$master" > named-zones-generated.conf
cd ..
