#!/bin/bash

set -o noglob
if test -z "$USER" ;then
  echo "USER not set" 1>&2
  exit 1
fi
usage="Usage: $0 username [-l] [NONE]|[+-]groups..."
case "$1" in
   -*) echo "$usage"; exit 1;;
esac


username=$1;shift
if test -z "$1" ;then
   echo "$usage"
   exit 1
fi

host=ldap.gnmedia.net
baseuserdn="ou=People,dc=gnmedia,dc=net"
basegroupdn="ou=Groups,dc=gnmedia,dc=net"
binddn="uid=$USER,$baseuserdn"

echo -n "($binddn)'s LDAP password: "
stty -echo
read password
stty echo
echo

ldapargs="-D $binddn -h $host"
openldapargs="-w $password -x $ldapargs"

testlist=$(ldapsearch $openldapargs -LLL -b $basegroupdn "(memberUid=$username)" cn)
if [ $? != 0 ];then
   exit 1
fi
if [ "$1" = "-l" ];then
   echo "$testlist"
   exit
fi
primarygid=$(ldapsearch $openldapargs -LLL -b $baseuserdn "(uid=$username)" gidNumber | grep ^gidNumber | awk '{print $2}')
primarygroup=$(ldapsearch $openldapargs -LLL -b $basegroupdn "(gidNumber=$primarygid)" cn | grep ^cn | awk '{print $2}')
for group in "$@";do
   case $group in
       -*) # remove it
           group=${group/-/}
           ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(memberUid=$username)" memberUid | grep -q ^memberUid && \
           echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: memberUid\nmemberUid: $username" | ldapmodify $openldapargs
           ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(uniqueMember=uid=$username,$baseuserdn)" uniqueMember | grep -q ^uniqueMember && \
           echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: uniqueMember\nuniqueMember: uid=$username,$baseuserdn" | ldapmodify $openldapargs
           ;;
       NONE) # remove all
           for group in $(ldapsearch $openldapargs -LLL "(memberUid=$username)" cn | grep ^cn | awk '{print $2}');do
              ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(memberUid=$username)" memberUid | grep -q ^memberUid && \
              echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: memberUid\nmemberUid: $username" | ldapmodify $openldapargs
              ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(uniqueMember=uid=$username,$baseuserdn)" uniqueMember | grep -q ^uniqueMember && \
              echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\ndelete: uniqueMember\nuniqueMember: uid=$username,$baseuserdn" | ldapmodify $openldapargs
           done
           ;;
       ALL) # really?
           echo "No, that's dumb."; exit 1
           ;;
       *) # add it
           group=${group/+/}
           if [ "$primarygroup" != "$group" ];then
              # There is no need to add users to their own primary group
              ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(memberUid=$username)" memberUid | grep -q ^memberUid || \
              echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\nadd: memberUid\nmemberUid: $username" | ldapmodify $openldapargs
              ldapsearch $openldapargs -LLL -b cn=$group,$basegroupdn "(uniqueMember=uid=$username,$baseuserdn)" uniqueMember | grep -q ^uniqueMember || \
              echo -e "dn: cn=$group,$basegroupdn\nchangetype: modify\nadd: uniqueMember\nuniqueMember: uid=$username,$baseuserdn" | ldapmodify $openldapargs
           fi
           ;;
   esac
done 

echo
echo "Listing current group memberships..."
ldapsearch $openldapargs -LLL -b $basegroupdn "(memberUid=$username)" cn

accessconfgen
