#!/usr/bin/perl -i

# replace NFS devices in manifests with the latest and greatest style
# Won't change comments.
# Won't replace if vol2newdest fails

while (<>) {

/(.*)/;
$data=$1;
$data=~ s/#.*//;
if ($data =~ m/device\s*=>\s[\"\']([^\"\']+)[\"\']/) {
   $olddevice=$1;
   if ($olddevice =~ /:/) {
      $olddevice =~ s/\$/\\\$/;
      #print STDERR "Device --> $olddevice\n";
      $newdevice=`vol2newdest '$olddevice'`;
      $newdevice =~ s/\\\$/\$/;
      chomp($newdevice);
      #print STDERR "    -> $newdevice\n";
      if ($newdevice !~ m/FAIL/) {
         s{$olddevice}{$newdevice};
      } else {
         print STDERR "$ARGV $olddevice $newdevice\n";
      }
   }
}
print "$_";

}
