#!/bin/bash

cd /$XCATROOT

if [ -z "$DAEMONIZED" ];then
   echo Daemonizing...
   export DAEMONIZED=1
   ($0 </dev/null >/dev/null 2>&1 &) </dev/null >/dev/null 2>&1 &
   exit
fi

unset DAEMONIZED
echo Done.
while sleep 180;do
   metalrebalance >> /var/log/metalrebalance.log 2>&1
done
