#!/bin/bash

sourcefiler=${1%:*}
sourcefullpath=${1#*:}
sourcevol=$(echo $sourcefullpath | cut -d / -f 3)
sourcesubdir=$(echo $sourcefullpath | cut -d / -f 4-)
destfiler=${2%:*}
destfullpath=${2#*:}
destvol=$(echo $destfullpath | cut -d / -f 3)
destsubdir=$(echo $destfullpath | cut -d / -f 4-)

if [ "$3" == "-complete" ];then
   complete=yes
fi

if [ -z "$destvol" ];then
   echo "Usage: $0 <filer:sourcepath> <filer:destinationpath> [-complete]"
   exit 1
fi

case $destfiler in
   nfs1-netapp1.*) aggr=netapp1_01_aggr1;;
   nfs2-netapp1.*) aggr=netapp1_02_aggr1;;
   *) aggr=data1;;
esac
case $destvol in
   nac1a*) aggr=netapp1_01_aggr1;;
   nac1b*) aggr=netapp1_02_aggr1;;
   *) echo "can't determine aggregate from $destvol\n"; exit 1;;
esac



exports=$(rnetapp $sourcefiler exports list /vol/$sourcevol | grep read-write | cut -d : -f 2)


## Only setup the SM relationship if the dest volume doesn't exist
if ! rnetapp $destfiler volume list $destvol >/dev/null;then
   size=$(rnetapp $sourcefiler vol size $sourcevol | cut -d : -f 2 | xargs echo)
   if [ -z "$size" ];then
      exit;
   fi
   reserve=$(rnetapp $sourcefiler snapshot reserve $sourcevol | sed -e 's/.*snapshot reserve is \(.*\)% or .*/\1/')
   if [ -z "$reserve" ];then
      exit;
   fi

   echo "Size/reserve: $size/$reserve"
   echo "Aggr: $aggr"
   echo "Exports: $exports"

   rnetapp $destfiler volume create $destvol $size $aggr dp
   rnetapp $destfiler snapshot reserve $destvol $reserve
   rnetapp $destfiler snapmirror create -t tdp -S $sourcefiler:$sourcefullpath netapp1_nfs:$destfullpath 
   rnetapp $destfiler snapmirror wait  netapp1_nfs:$destvol 
else
   echo "Dest volume exists; not setting up a snapmirror relationship"
   ##  Do an update, but first wait for any pending updates already in progress
   rnetapp $destfiler snapmirror wait  netapp1_nfs:$destvol 
   rnetapp $destfiler snapmirror update -w  netapp1_nfs:$destvol 
fi




## Maybe finish things
if [ "$complete" == "yes" ];then
   rnetapp $destfiler snapmirror wait  netapp1_nfs:$destvol 
   
   echo "Waiting 5 secs..."
   sleep 5
   rnetapp $sourcefiler snapmirror release -s $sourcevol -d netapp1_nfs:$destvol
   rnetapp $destfiler snapmirror break  netapp1_nfs:$destvol 
   rnetapp $destfiler snapmirror delete  netapp1_nfs:$destvol 

   echo "Waiting 5 secs..."
   sleep 5
   for exp in $exports;do
      rnetapp $destfiler exports add /vol/$destvol $exp
   done
   rnetapp $destfiler vol option $destvol fs_size_fixed off
   rnetapp $destfiler snapshot delete $destvol ALL
fi

